### ISSUE TITLE
Deprecated selector in `monokai-dave\index.less`

### ISSUE THREAD

**Issue by farookhridoy** [quarterto/Monokai-Dave#1]
In `monokai-dave\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .gutter,
:host .gutter` => `atom-text-editor .gutter,atom-text-editor .gutter`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .search-results .marker .region,
:host .search-results .marker .region` => `atom-text-editor .search-results .syntax--marker .region,atom-text-editor .search-results .syntax--marker .region`

* `atom-text-editor .search-results .marker.current-result .region,
:host .search-results .marker.current-result .region` => `atom-text-editor .search-results .syntax--marker.current-result .region,atom-text-editor .search-results .syntax--marker.current-result .region`

* `atom-text-editor.is-focused .cursor,
:host(.is-focused) .cursor` => `atom-text-editor.is-focused .cursor,atom-text-editor .cursor`

* `atom-text-editor.is-focused .selection .region,
:host(.is-focused) .selection .region` => `atom-text-editor.is-focused .selection .region,atom-text-editor .selection .region`

* `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,
:host(.is-focused) .line-number.cursor-line-no-selection,
:host(.is-focused) .line.cursor-line` => `atom-text-editor.is-focused .line-number.cursor-line-no-selection,
atom-text-editor.is-focused .line.cursor-line,atom-text-editor .line-number.cursor-line-no-selection,atom-text-editor .line.cursor-line`

* `.meta.diff,
.meta.diff.header` => `.syntax--meta.syntax--diff,
.syntax--meta.syntax--diff.syntax--header`

* `.markup.deleted` => `.syntax--markup.syntax--deleted`

* `.markup.inserted` => `.syntax--markup.syntax--inserted`

* `.markup.changed` => `.syntax--markup.syntax--changed`

* `.comment` => `.syntax--comment`

* `.string` => `.syntax--string`

* `.constant.numeric` => `.syntax--constant.syntax--numeric`

* `.constant.language` => `.syntax--constant.syntax--language`

* `.constant.character,
.constant.other` => `.syntax--constant.syntax--character,
.syntax--constant.syntax--other`

* `.variable` => `.syntax--variable`

* `.keyword` => `.syntax--keyword`

* `.storage` => `.syntax--storage`

* `.storage.type` => `.syntax--storage.syntax--type`

* `.entity.name.class` => `.syntax--e

**Comment by apaleslimghost** [comment]
Thanks @gmfaruk, but I don't use this theme any more and I'm not interested in maintaining it (it was autoconverted from a Sublime Text theme several years ago, and I've since hand-built an improved version, [makika-syntax](https://atom.io/packages/makika-syntax)). If you'd like to take on maintainership of this repo I'd be happy to give you access, but for now I'm just going to close this and archive the repo.
